### ISSUE TITLE
Compile failure since 62ff26b70dbe377cffe97b999c7865825132a61d

### ISSUE THREAD

**Issue by koenkooi** [treymarc/multiwii-mavlink-gc#2]
Both log2cvs and mwgc don't compile due to the debug1, debug2, debug3 and debug4:

le/log2csv.c -o src/example/log2csv.o
src/example/log2csv.c:108:51: error: no member named 'debug1' in 'mwi_uav_state_t'; did you mean 'debug'?
                                mwiState->rcAUX3, mwiState->rcAUX4, mwiState->debug1,
                                                                              ^~~~~~
                                                                              debug
src/example/../mwi/mwi.h:33:6: note: 'debug' declared here
        int debug[4];
            ^
src/example/log2csv.c:109:15: error: no member named 'debug2' in 'mwi_uav_state_t'; did you mean 'debug'?
                                mwiState->debug2, mwiState->debug3, mwiState->debug4);
                                          ^~~~~~
                                          debug
src/example/../mwi/mwi.h:33:6: note: 'debug' declared here
        int debug[4];
            ^
src/example/log2csv.c:109:33: error: no member named 'debug3' in 'mwi_uav_state_t'; did you mean 'debug'?
                                mwiState->debug2, mwiState->debug3, mwiState->debug4);
                                                            ^~~~~~
                                                            debug
src/example/../mwi/mwi.h:33:6: note: 'debug' declared here
        int debug[4];
            ^
src/example/log2csv.c:109:51: error: no member named 'debug4' in 'mwi_uav_state_t'; did you mean 'debug'?
                                mwiState->debug2, mwiState->debug3, mwiState->debug4);
                                                                              ^~~~~~
                                                                              debug
src/example/../mwi/mwi.h:33:6: note: 'debug' declared here
        int debug[4];

**Comment by treymarc** [comment]
mwiState->debug2, mwiState->debug3, mwiState->debug4 is wrong , this is now solved
